version: '3.8'

volumes:
    postgres:
services:
    db:
        image: postgres:12.0
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - ./.env
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        image: nginx:1.19.3
        ports:
            - "80:80"
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - api

